-- NOIR • I ZI authenticated email/password registration
--
-- Keeps NOIR closed to signed-out visitors while allowing future, non-anonymous
-- Auth users to enter as ordinary players. Existing blocked profiles are not
-- bulk-approved, and browser clients cannot promote themselves to admin.

begin;

create or replace function public.register_new_noir_player()
returns trigger
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  player_nickname text;
begin
  if new.email is null
     or trim(new.email) = ''
     or coalesce(new.is_anonymous, false) is true
  then
    return new;
  end if;

  player_nickname :=
    left(
      coalesce(
        nullif(
          trim(new.raw_user_meta_data ->> 'nickname'),
          ''
        ),
        nullif(split_part(new.email, '@', 1), ''),
        'Player'
      ),
      30
    );

  insert into public.profiles (
    user_id,
    nickname,
    role,
    is_admin,
    access_approved,
    last_active_at
  )
  values (
    new.id,
    player_nickname,
    'player',
    false,
    true,
    now()
  )
  on conflict (user_id) do update
  set access_approved = true,
      last_active_at = now();

  return new;
end;
$$;

revoke all on function public.register_new_noir_player()
  from public, anon, authenticated;

drop trigger if exists register_new_noir_player
  on auth.users;
create trigger register_new_noir_player
after insert on auth.users
for each row
execute function public.register_new_noir_player();

create table if not exists public.noir_registration_attempts (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  attempted_at timestamptz not null default now()
);

create index if not exists noir_registration_attempts_ip_time_idx
  on public.noir_registration_attempts (
    ip_hash,
    attempted_at desc
  );

alter table public.noir_registration_attempts
  enable row level security;

revoke all on table public.noir_registration_attempts
  from public, anon, authenticated;
grant select, insert, delete
  on table public.noir_registration_attempts
  to service_role;

grant usage, select
  on sequence public.noir_registration_attempts_id_seq
  to service_role;

create or replace function public.claim_noir_registration(
  p_ip_hash text
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  recent_network_attempts integer;
  recent_global_attempts integer;
begin
  if p_ip_hash is null
     or length(trim(p_ip_hash)) < 32
  then
    return false;
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(
      'noir-registration-global',
      0
    )
  );

  delete from public.noir_registration_attempts
  where attempted_at < now() - interval '7 days';

  select count(*)
  into recent_network_attempts
  from public.noir_registration_attempts
  where ip_hash = p_ip_hash
    and attempted_at >= now() - interval '1 hour';

  select count(*)
  into recent_global_attempts
  from public.noir_registration_attempts
  where attempted_at >= now() - interval '1 day';

  if recent_network_attempts >= 10
     or recent_global_attempts >= 200
  then
    return false;
  end if;

  insert into public.noir_registration_attempts (
    ip_hash
  )
  values (
    p_ip_hash
  );

  return true;
end;
$$;

revoke all on function public.claim_noir_registration(text)
  from public, anon, authenticated;
grant execute on function public.claim_noir_registration(text)
  to service_role;

commit;
